
spring:
  batch:
    job:
      enabled: false      # 자동 Job 실행 비활성화
    jdbc:
      initialize-schema: never
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.0.2:5432/postgres
    username: postgres
    password: 1234

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

    sql:
      init:
        mode: always
  data:
    redis:
      host: 192.168.0.2
      port: 6379
      password:   # 필요시
      database: 0
      timeout: 3000ms

      # Connection Pool 설정 (Lettuce 기본)
      lettuce:
        pool:
          max-active: 10 # 최대 커넥션 수
          max-idle: 10
          min-idle: 1
          max-wait: -1ms

file:
  upload:
    path: ./uploads/
    allowed-extensions: jpg,jpeg,png,gif,pdf,doc,docx,xls,xlsx
    max-size: 10485760  # 10MB
server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:MySecretKeyForJWT123456789012345678901234567890123456789012345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000} # 24시간


#logging:
#  level:
#    org.springframework.aop: DEBUG

turnstile:
  site-key: "0x4AAAAAACFMTZwKlBaviRvl"
  secret-key: "0x4AAAAAACFMTfqpFX0i2s1eYyRCCPscmsI"